fix: use current selenium api
I tried the demo and it failed saying, "AttributeError: 'WebDriver' object has no attribute 'find_element_by_tag_name'"

It looks like the deprecated `find_element_by_*` methods have been removed in Selenium 4.3.0.

This commit replaces all the usages of those deprecated methods with their current alternatives.

Refs: https://stackoverflow.com/a/72773269/5432315